power<-read.table("household_power_consumption.txt",header = TRUE, sep = ";",stringsAsFactors = FALSE,dec = ".")
subsetpower<-power[power$Date %in% c("1/2/2007","2/2/2007"),]
globalactivepower<-as.numeric(subsetpower$Global_active_power)
submetring1<-as.numeric(subsetpower$Sub_metering_1)
submetring2<-as.numeric(subsetpower$Sub_metering_2)
submetring3<-as.numeric(subsetpower$Sub_metering_3)
datetime<-strptime(paste(subsetpower$Date,subsetpower$Time,sep = " "),"%d/%m/%Y %H:%M:%S")
plot(datetime,submetring1,type = "l", xlab = " ",ylab = "Energy submetring")
lines(datetime,submetring2,type = "l",col="red")
lines(datetime,submetring3,type = "l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metring_2","Sub_metering_3"),lty = 1,lwd=2,col=c("black","red","blue"))
dev.copy(png,file="plot3.png",height=480,width=480)
dev.off()